name: Josh Deploy

on:
  push:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create Supabase Config
        run: |
          cat > supabase-config.js << 'EOL'
          // Supabase configuration
          window.supabaseConfig = {
            supabaseUrl: "${{ secrets.SUPABASE_URL }}",
            supabaseKey: "${{ secrets.SUPABASE_KEY }}"
          };
          
          // Initialize Supabase client
          window.initSupabase = function() {
            try {
              window.supabaseClient = supabase.createClient(
                window.supabaseConfig.supabaseUrl,
                window.supabaseConfig.supabaseKey
              );
              console.log("Supabase client initialized");
              return true;
            } catch (error) {
              console.error("Failed to initialize Supabase client:", error);
              window.supabaseClient = null;
              return false;
            }
          };
          EOL

    - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: web-build-artifact  # the name of the artifact
          path: build/web
  deploy:
    needs: build
    
    runs-on: ubuntu-latest
    
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5
        
      - name: Deploy to GitHub Pages 🚀
        if: github.event_name == 'push'  # deploy only on push
        id: deployment
        uses: actions/deploy-pages@v4.0.5
        with:
          artifact_name: web-build-artifact
